export const REQUEST_USER_LIST_TO_SPRING = 'REQUEST_USER_LIST_TO_SPRING'
export const REQUEST_USER_TO_SPRING = 'REQUEST_USER_TO_SPRING'

export const SET_ACCESS_TOKEN = "SET_ACCESS_TOKEN"
export const SET_USER = "SET_USER"
export const SET_SIGNIN = "SET_SIGNIN"
export const SET_BLOCK_USERS = "SET_BLOCK_USERS"
export const SET_FOLLOW_USERS = "SET_FOLLOW_USERS"